version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres

  postgres:
    build: .docker/postgres
    container_name: api-postgres
    restart: always
    tty: true
    ports:
      - '1111:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apivendas
